/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as FacilitatorRouteImport } from './routes/facilitator'
import { Route as DiagramRouteImport } from './routes/diagram'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as FacilitatorDiagramRouteImport } from './routes/facilitator.diagram'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitatorRoute = FacilitatorRouteImport.update({
  id: '/facilitator',
  path: '/facilitator',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramRoute = DiagramRouteImport.update({
  id: '/diagram',
  path: '/diagram',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)
const FacilitatorDiagramRoute = FacilitatorDiagramRouteImport.update({
  id: '/diagram',
  path: '/diagram',
  getParentRoute: () => FacilitatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagram': typeof DiagramRoute
  '/facilitator': typeof FacilitatorRouteWithChildren
  '/framework': typeof FrameworkRoute
  '/join': typeof JoinRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/facilitator/diagram': typeof FacilitatorDiagramRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagram': typeof DiagramRoute
  '/facilitator': typeof FacilitatorRouteWithChildren
  '/framework': typeof FrameworkRoute
  '/join': typeof JoinRoute
  '/facilitator/diagram': typeof FacilitatorDiagramRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagram': typeof DiagramRoute
  '/facilitator': typeof FacilitatorRouteWithChildren
  '/framework': typeof FrameworkRoute
  '/join': typeof JoinRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/facilitator/diagram': typeof FacilitatorDiagramRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagram'
    | '/facilitator'
    | '/framework'
    | '/join'
    | '/sessions'
    | '/facilitator/diagram'
    | '/sessions/$id'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagram'
    | '/facilitator'
    | '/framework'
    | '/join'
    | '/facilitator/diagram'
    | '/sessions/$id'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/diagram'
    | '/facilitator'
    | '/framework'
    | '/join'
    | '/sessions'
    | '/facilitator/diagram'
    | '/sessions/$id'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagramRoute: typeof DiagramRoute
  FacilitatorRoute: typeof FacilitatorRouteWithChildren
  FrameworkRoute: typeof FrameworkRoute
  JoinRoute: typeof JoinRoute
  SessionsRoute: typeof SessionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitator': {
      id: '/facilitator'
      path: '/facilitator'
      fullPath: '/facilitator'
      preLoaderRoute: typeof FacilitatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagram': {
      id: '/diagram'
      path: '/diagram'
      fullPath: '/diagram'
      preLoaderRoute: typeof DiagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/facilitator/diagram': {
      id: '/facilitator/diagram'
      path: '/diagram'
      fullPath: '/facilitator/diagram'
      preLoaderRoute: typeof FacilitatorDiagramRouteImport
      parentRoute: typeof FacilitatorRoute
    }
  }
}

interface FacilitatorRouteChildren {
  FacilitatorDiagramRoute: typeof FacilitatorDiagramRoute
}

const FacilitatorRouteChildren: FacilitatorRouteChildren = {
  FacilitatorDiagramRoute: FacilitatorDiagramRoute,
}

const FacilitatorRouteWithChildren = FacilitatorRoute._addFileChildren(
  FacilitatorRouteChildren,
)

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagramRoute: DiagramRoute,
  FacilitatorRoute: FacilitatorRouteWithChildren,
  FrameworkRoute: FrameworkRoute,
  JoinRoute: JoinRoute,
  SessionsRoute: SessionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
